### ISSUE TITLE
Issue with Wyoming water rights data for agricultural data?

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/MappingStatesDataToWaDE2.0#74]
If you select only agricultural beneficial use (leave all other filters as-is), then Wyoming mostly shows no water rights for agriculture. E.g., I know that the Bear River Watershed on the WY side does have agriculture. There could be an issue in mapping or loading the beneficial uses. It could be a database loader issue. Something to look into

https://wade-mapbox-prototype.azureedge.net/
![image](https://user-images.githubusercontent.com/3268971/105913496-26a0f200-5fea-11eb-8069-956a1141d218.png)

**Comment by rwjam** [comment]
Issue of how we were handling the source data.  Accidently clipping records with multiple beneficial uses listed without meaning.  That issue has been resolved.

Turns out the original WY-Beneficial Use dictionary we were using wasn't very clean either (i.e., unnecessary duplicates, special characters, etc).  I decided to clean up the data to get it to a point where it was clean and an easy ready into WaDE 2.0.  This **DOES** mean we have transformed the original source data away from it's original format, which we should bring up with WY and make sure they are okay with.

Including these changes have increased the amount of agricultural ben use sites that can be viewed in WY (see image below).

![image](https://user-images.githubusercontent.com/17555073/107083770-5b176980-67b3-11eb-9361-77d0df2cf084.png)
